// @ts-nocheck
import L from "leaflet";
import "./style.css";

const STORAGE="okinawa-cycle-guide-state";
const GEO_CACHE="okinawa-cycle-guide-hotel-geocode-v1";
const fallback=[
 {day:1,title:"那霸 → 恩納（西海岸）",description:"波上宮、浦添、宜野灣、北谷、殘波岬、恩納",distanceKm:75,waypoints:[{name:"那霸",lat:26.218,lon:127.6713},{name:"殘波岬",lat:26.441,lon:127.7145},{name:"恩納",lat:26.497,lon:127.8502}]},
 {day:2,title:"恩納 → 本部 → 古宇利 → 名護",description:"名護、本部、古宇利大橋",distanceKm:98,waypoints:[{name:"恩納",lat:26.497,lon:127.8502},{name:"本部",lat:26.6944,lon:127.878},{name:"古宇利",lat:26.7068,lon:128.0162},{name:"名護",lat:26.5915,lon:127.9773}]},
 {day:3,title:"名護 → 邊戶岬 → 國頭",description:"山原、國頭、邊戶岬",distanceKm:102,waypoints:[{name:"名護",lat:26.5915,lon:127.9773},{name:"邊戶岬",lat:26.8723,lon:128.2632},{name:"國頭",lat:26.7454,lon:128.1777}]},
 {day:4,title:"國頭 → 東村 → 宇流麻 → 南城",description:"東岸、海中道路、南城",distanceKm:115,waypoints:[{name:"國頭",lat:26.7454,lon:128.1777},{name:"東村",lat:26.633,lon:128.157},{name:"海中道路",lat:26.3278,lon:127.9277},{name:"南城",lat:26.1648,lon:127.7814}]},
 {day:5,title:"南城 → 知念 → 糸滿 → 那霸",description:"齋場御嶽、知念岬、糸滿、豐見城",distanceKm:80,waypoints:[{name:"南城",lat:26.1648,lon:127.7814},{name:"知念岬",lat:26.1678,lon:127.8317},{name:"糸滿",lat:26.1236,lon:127.6657},{name:"那霸",lat:26.2124,lon:127.6809}]}
];
const poke=[["那霸 ①","Growlithe",26.22005,127.71657],["那霸 ②","Arcanine",26.21641,127.68942],["浦添","Solrock + Skiploom",26.245559,127.687899],["宜野灣","Corsola + Luvdisc",26.28139,127.732214],["北谷","Growlithe",26.315733,127.753613],["沖繩市","Thwackey + Lurantis",26.32766,127.803001],["宇流麻","Tauros",26.436181,127.826113],["名護","Emolga + Pikipek",26.587352,127.985744],["本部","Wailord",26.691694,127.877972],["南城","Seviper + Zangoose",26.169111,127.827083],["糸滿","Wartortle + Sandygast",26.13828,127.661336],["豐見城","Axew + Jangmo-o",26.157556,127.656121]];
const hotels=[{dates:"10/10、10/15–10/18",area:"那霸市",name:"コンフォートホテル那覇県庁前",query:"コンフォートホテル那覇県庁前 沖縄",fallback:[26.2124,127.6809]},{dates:"10/11",area:"今歸仁村",name:"Villa Nakijin COCONUT JUNGLIA Okinawa",query:"Villa Nakijin COCONUT JUNGLIA Okinawa",fallback:[26.682,127.972]},{dates:"10/12",area:"國頭村",name:"Yanbaru Hostel",query:"Yanbaru Hostel Okinawa",fallback:[26.7454,128.1777]},{dates:"10/13",area:"金武町",name:"ASBO STAY HOTEL",query:"ASBO STAY HOTEL Okinawa",fallback:[26.456,127.926]},{dates:"10/14",area:"八重瀨町",name:"Unwind DAY OFF Nagamo",query:"Unwind DAY OFF Nagamo Okinawa",fallback:[26.158,127.72]}];
const prep=[["車況","外胎、煞車、變速、鏈條、螺絲"],["爆胎","內胎／補胎工具、撬胎棒、CO₂ 或打氣筒"],["電力","碼表、前後燈、行動電源、充電線"],["天候","薄雨衣、防曬、袖套、電解質"],["導航","GPX 已下載到碼表／手機，另有離線備份"],["證件／保險","護照、旅遊／單車保險資料"]];
const $=(s:string)=>document.querySelector(s) as HTMLElement;
function mapsUrl(q:string){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;}
function state(){try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}}
function save(){const s=state();document.querySelectorAll<HTMLInputElement>("[data-save]").forEach(x=>s[x.dataset.save!]=x.checked);localStorage.setItem(STORAGE,JSON.stringify(s));updateProgress();}
function restore(){const s=state();document.querySelectorAll<HTMLInputElement>("[data-save]").forEach(x=>x.checked=!!s[x.dataset.save!]);updateProgress();}
async function loadRoutes(){try{const r=await fetch(`${import.meta.env.BASE_URL}data/routes.json`,{cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();if(!Array.isArray(d)||!d.length)throw new Error();return d.filter((x:any)=>x.type!=="rest");}catch{return fallback;}}
function routeKm(r:any){return Number(r.generatedDistanceKm??r.distanceKm??0)}
function routeLatLngs(r:any){const g=r.geojson;if(g?.type==="LineString")return g.coordinates.map(([lon,lat]:number[])=>[lat,lon]);if(g?.type==="MultiLineString")return g.coordinates.map((line:number[][])=>line.map(([lon,lat])=>[lat,lon]));return r.waypoints.map((p:any)=>[p.lat,p.lon]);}
function readGeo(){try{return JSON.parse(localStorage.getItem(GEO_CACHE)||"{}")}catch{return{}}}
async function hotelLocation(h:any){const c=readGeo();if(c[h.name])return {...c[h.name],approx:false};try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=jp&q=${encodeURIComponent(h.query)}`);const d=await r.json();if(d?.[0]){const v={lat:Number(d[0].lat),lon:Number(d[0].lon)};c[h.name]=v;localStorage.setItem(GEO_CACHE,JSON.stringify(c));return {...v,approx:false};}}catch{}return{lat:h.fallback[0],lon:h.fallback[1],approx:true};}
function storePopup(s:any){const km=Number(s.targetKm??s.routeProgressKm??0),p=Number(s.routeProgressKm??km),m=Number(s.distanceFromRouteM??0),name=s.displayName||s.name||s.brand||"便利商店";return `<b>🥤 約 ${km.toFixed(0)} km｜${name}</b><br>${s.address||""}<br><small>實際路線位置 ${p.toFixed(1)} km${m?` ・ 離路線約 ${Math.round(m)} m`:""}</small><br><a target="_blank" href="${s.googleMapsUrl||mapsUrl(`${s.lat},${s.lon}`)}">Google Maps ↗</a>`;}
function routeDetail(r:any){const stores=Array.isArray(r.convenienceStores)?r.convenienceStores:[],day=String(r.day).padStart(2,"0");return `<div class="day"><div class="badge">D${r.day}</div><div><h3>${r.title}</h3><div class="meta"><span>${routeKm(r)||"—"} km</span><span>補給點 ${stores.length}</span></div><p class="muted">${r.description||""}</p><a href="${import.meta.env.BASE_URL}routes/generated/day-${day}.gpx" download>下載 GPX</a></div></div>${stores.length?`<h4>每約 10 km 補給</h4><div class="grid g2">${stores.map((s:any)=>`<div class="poi"><span><b>${Math.round(Number(s.targetKm??s.routeProgressKm??0))} km｜${s.displayName||s.name||s.brand||"便利商店"}</b><br><span class="muted">${s.address||""}</span><br><a target="_blank" href="${s.googleMapsUrl||mapsUrl(`${s.lat},${s.lon}`)}">Google Maps ↗</a></span></div>`).join("")}</div>`:`<p class="muted">便利商店資料正在更新。</p>`}`;}
async function renderRouteMap(routes:any[]){$("#total-km").textContent=`${routes.reduce((s,r)=>s+routeKm(r),0).toFixed(1)} km`;$("#ride-days").textContent=`${routes.length} days`;const map=L.map("map",{scrollWheelZoom:false}).setView([26.48,127.93],9);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap contributors"}).addTo(map);const routeLayer=L.layerGroup().addTo(map),storeLayer=L.layerGroup().addTo(map),hotelLayer=L.layerGroup().addTo(map),pokeLayer=L.layerGroup().addTo(map);L.control.layers(undefined,{"單車路線":routeLayer,"每 10 km 便利商店":storeLayer,"住宿":hotelLayer,"Poké Lids":pokeLayer},{collapsed:false}).addTo(map);const colors=["#0077b6","#00a896","#f4a261","#e76f51","#7b2cbf"];
 const draw=(day:number|null)=>{routeLayer.clearLayers();storeLayer.clearLayers();const active=day==null?routes:routes.filter(r=>r.day===day),bounds:any[]=[];active.forEach(r=>{const color=colors[(r.day-1)%colors.length],ll=routeLatLngs(r);if(r.geojson?.type==="MultiLineString")ll.forEach((line:any)=>L.polyline(line,{color,weight:6,opacity:.9}).addTo(routeLayer));else L.polyline(ll,{color,weight:6,opacity:.9}).addTo(routeLayer);(r.waypoints||[]).forEach((w:any,wi:number)=>{L.circleMarker([w.lat,w.lon],{radius:wi===0?7:5,color:"#fff",weight:2,fillColor:color,fillOpacity:1}).bindPopup(`${wi===0?"🚩 起點<br>":""}${w.name}`).addTo(routeLayer);bounds.push([w.lat,w.lon]);});(r.convenienceStores||[]).forEach((s:any)=>{L.circleMarker([s.lat,s.lon],{radius:7,color:"#fff",weight:2,fillColor:"#16a34a",fillOpacity:1}).bindPopup(storePopup(s)).addTo(storeLayer);bounds.push([s.lat,s.lon]);});});if(bounds.length)map.fitBounds(bounds,{padding:[24,24]});$("#route-detail").innerHTML=day==null?`<h3>全部路線</h3><p class="muted">選擇 Day 可聚焦單日路線與每約 10 km 補給點。</p>`:routeDetail(routes.find(r=>r.day===day));};
 const tabs=$("#day-tabs");tabs.innerHTML=`<button class="button" data-day="all">全部</button>`+routes.map(r=>`<button class="button" data-day="${r.day}">Day ${r.day}</button>`).join("");tabs.querySelectorAll<HTMLElement>("[data-day]").forEach(b=>b.addEventListener("click",()=>draw(b.dataset.day==="all"?null:Number(b.dataset.day))));
 (await Promise.all(hotels.map(async h=>({h,l:await hotelLocation(h)})))).forEach(({h,l})=>L.circleMarker([l.lat,l.lon],{radius:8,color:"#fff",weight:2,fillColor:"#d97706",fillOpacity:1}).bindPopup(`<b>🏨 ${h.name}</b><br>${h.dates} ・ ${h.area}<br><a target="_blank" href="${mapsUrl(h.query)}">Google Maps ↗</a>`).addTo(hotelLayer));poke.forEach(([name,mons,lat,lon])=>L.circleMarker([lat,lon],{radius:7,color:"#fff",weight:2,fillColor:"#7c3aed",fillOpacity:1}).bindPopup(`<b>🕳️ ${name}</b><br>${mons}<br><a target="_blank" href="https://www.google.com/maps?q=${lat},${lon}">Google Maps ↗</a>`).addTo(pokeLayer));draw(1);}
function renderLists(){$("#poke-list").innerHTML=poke.map(([name,mons,lat,lon],i)=>`<label class="poi"><input type="checkbox" data-save="poke-${i}" data-group="poke"><span><b>${name}</b><br><span class="muted">${mons}</span><br><a target="_blank" href="https://www.google.com/maps?q=${lat},${lon}">地圖 ↗</a></span></label>`).join("");$("#prep-list").innerHTML=prep.map(([n,d],i)=>`<label class="poi"><input type="checkbox" data-save="prep-${i}"><span><b>${n}</b><br><span class="muted">${d}</span></span></label>`).join("");document.querySelectorAll<HTMLInputElement>("[data-save]").forEach(x=>x.addEventListener("change",save));restore();}
function updateProgress(){const n=[...document.querySelectorAll<HTMLInputElement>('[data-group="poke"]')].filter(x=>x.checked).length;$("#poke-count").textContent=`${n} / ${poke.length}`;($("#poke-bar") as HTMLElement).style.width=`${n/poke.length*100}%`;$("#cert-poke").textContent=`${n} / ${poke.length}`;}
function setupCertificate(){($("#cert-update") as HTMLButtonElement).addEventListener("click",()=>{$("#cert-name-out").textContent=(($("#cert-name") as HTMLInputElement).value.trim()||"RR");$("#cert-date-out").textContent="完成日期："+((($("#cert-date") as HTMLInputElement).value)||"—");$("#cert-km-out").textContent=((($("#cert-km") as HTMLInputElement).value)||"—")+" km";$("#cert-elev-out").textContent=((($("#cert-elev") as HTMLInputElement).value)||"—")+" m";updateProgress();});}
(async()=>{renderLists();setupCertificate();await renderRouteMap(await loadRoutes());})();