import L from "leaflet";
import "./style.css";

type Waypoint={name:string;lat:number;lon:number};
type RouteGeometry={type:"LineString"|"MultiLineString";coordinates:[number,number][]|[number,number][][]};
type RouteDay={day:number;type?:string;title:string;description:string;distanceKm:number|null;generatedDistanceKm?:number|null;waypoints:Waypoint[];geojson?:RouteGeometry|null;convenienceStores?:unknown[]};
type Hotel={dates:string;area:string;name:string;query:string;fallback:[number,number]};

const STORAGE="okinawa-cycle-guide-state";
const GEO_CACHE="okinawa-cycle-guide-hotel-geocode-v1";
const fallback:RouteDay[]=[
 {day:1,title:"那霸 → 恩納（西海岸）",description:"波上宮、浦添、宜野灣、北谷、殘波岬、恩納",distanceKm:75,waypoints:[{name:"那霸",lat:26.218,lon:127.6713},{name:"殘波岬",lat:26.441,lon:127.7145},{name:"恩納",lat:26.497,lon:127.8502}]},
 {day:2,title:"恩納 → 本部 → 古宇利 → 名護",description:"名護、本部、古宇利大橋",distanceKm:98,waypoints:[{name:"恩納",lat:26.497,lon:127.8502},{name:"本部",lat:26.6944,lon:127.878},{name:"古宇利",lat:26.7068,lon:128.0162},{name:"名護",lat:26.5915,lon:127.9773}]},
 {day:3,title:"名護 → 邊戶岬 → 國頭",description:"山原、國頭、邊戶岬",distanceKm:102,waypoints:[{name:"名護",lat:26.5915,lon:127.9773},{name:"邊戶岬",lat:26.8723,lon:128.2632},{name:"國頭",lat:26.7454,lon:128.1777}]},
 {day:4,title:"國頭 → 東村 → 宇流麻 → 南城",description:"東岸、海中道路、南城",distanceKm:115,waypoints:[{name:"國頭",lat:26.7454,lon:128.1777},{name:"東村",lat:26.633,lon:128.157},{name:"海中道路",lat:26.3278,lon:127.9277},{name:"南城",lat:26.1648,lon:127.7814}]},
 {day:5,title:"南城 → 知念 → 糸滿 → 那霸",description:"齋場御嶽、知念岬、糸滿、豐見城",distanceKm:80,waypoints:[{name:"南城",lat:26.1648,lon:127.7814},{name:"知念岬",lat:26.1678,lon:127.8317},{name:"糸滿",lat:26.1236,lon:127.6657},{name:"那霸",lat:26.2124,lon:127.6809}]}
];
const poke=[
 ["那霸 ①","Growlithe",26.22005,127.71657],["那霸 ②","Arcanine",26.21641,127.68942],["浦添","Solrock + Skiploom",26.245559,127.687899],["宜野灣","Corsola + Luvdisc",26.28139,127.732214],["北谷","Growlithe",26.315733,127.753613],["沖繩市","Thwackey + Lurantis",26.32766,127.803001],["宇流麻","Tauros",26.436181,127.826113],["名護","Emolga + Pikipek",26.587352,127.985744],["本部","Wailord",26.691694,127.877972],["南城","Seviper + Zangoose",26.169111,127.827083],["糸滿","Wartortle + Sandygast",26.13828,127.661336],["豐見城","Axew + Jangmo-o",26.157556,127.656121]
] as const;
const hotels:Hotel[]=[
 {dates:"10/10、10/15–10/18",area:"那霸市",name:"コンフォートホテル那覇県庁前",query:"コンフォートホテル那覇県庁前 沖縄",fallback:[26.2124,127.6809]},
 {dates:"10/11",area:"今歸仁村",name:"Villa Nakijin COCONUT JUNGLIA Okinawa",query:"Villa Nakijin COCONUT JUNGLIA Okinawa",fallback:[26.682,127.972]},
 {dates:"10/12",area:"國頭村",name:"Yanbaru Hostel",query:"Yanbaru Hostel Okinawa",fallback:[26.7454,128.1777]},
 {dates:"10/13",area:"金武町",name:"ASBO STAY HOTEL",query:"ASBO STAY HOTEL Okinawa",fallback:[26.456,127.926]},
 {dates:"10/14",area:"八重瀨町",name:"Unwind DAY OFF Nagamo",query:"Unwind DAY OFF Nagamo Okinawa",fallback:[26.158,127.72]}
];
const prep=[["車況","外胎、煞車、變速、鏈條、螺絲"],["爆胎","內胎／補胎工具、撬胎棒、CO₂ 或打氣筒"],["電力","碼表、前後燈、行動電源、充電線"],["天候","薄雨衣、防曬、袖套、電解質"],["導航","GPX 已下載到碼表／手機，另有離線備份"],["證件／保險","護照、旅遊／單車保險資料"]] as const;
const q=<T extends Element>(selector:string)=>document.querySelector(selector) as T;
function readState():Record<string,boolean>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}}
function save():void{const s=readState();document.querySelectorAll<HTMLInputElement>("[data-save]").forEach(x=>s[x.dataset.save!]=x.checked);localStorage.setItem(STORAGE,JSON.stringify(s));updateProgress();}
function restore():void{const s=readState();document.querySelectorAll<HTMLInputElement>("[data-save]").forEach(x=>x.checked=!!s[x.dataset.save!]);updateProgress();}
async function loadRoutes():Promise<RouteDay[]>{try{const response=await fetch(`${import.meta.env.BASE_URL}data/routes.json`,{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as RouteDay[];if(!Array.isArray(data)||!data.length)throw new Error();return data.filter(x=>x.type!=="rest");}catch{return fallback;}}
function routeKm(r:RouteDay):number{return Number(r.generatedDistanceKm??r.distanceKm??0)}
function routeLatLngs(r:RouteDay):L.LatLngExpression[]|L.LatLngExpression[][]{const g=r.geojson;if(g?.type==="LineString")return(g.coordinates as [number,number][]).map(([lon,lat])=>[lat,lon]);if(g?.type==="MultiLineString")return(g.coordinates as [number,number][][]).map(line=>line.map(([lon,lat])=>[lat,lon]));return r.waypoints.map(p=>[p.lat,p.lon]);}
function renderRoutes(routes:RouteDay[]):void{const total=routes.reduce((sum,r)=>sum+routeKm(r),0);q<HTMLElement>("#total-km").textContent=`${total.toFixed(1)} km`;q<HTMLElement>("#ride-days").textContent=`${routes.length} days`;q<HTMLElement>("#routes").innerHTML=routes.map(r=>{const day=String(r.day).padStart(2,"0");const stores=r.convenienceStores?.length??0;return `<article class="card day"><div class="badge">D${r.day}</div><div><h3>${r.title}</h3><div class="meta"><span>${routeKm(r)||"—"} km</span>${stores?`<span>補給候選 ${stores}</span>`:""}</div><p class="muted">${r.description||r.waypoints.map(w=>w.name).join(" → ")}</p><div class="tools"><a href="${import.meta.env.BASE_URL}routes/generated/day-${day}.gpx" download>下載 GPX</a><span class="muted">${r.waypoints.map(w=>w.name).join(" → ")}</span></div></div></article>`}).join("");}
function mapsUrl(query:string):string{return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;}
function readGeocodeCache():Record<string,{lat:number;lon:number}>{try{return JSON.parse(localStorage.getItem(GEO_CACHE)||"{}")}catch{return{}}}
async function hotelLocation(hotel:Hotel):Promise<{lat:number;lon:number;approx:boolean}>{const cache=readGeocodeCache();const cached=cache[hotel.name];if(cached)return{...cached,approx:false};try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=jp&q=${encodeURIComponent(hotel.query)}`,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error();const result=await response.json() as Array<{lat:string;lon:string}>;if(result[0]){const location={lat:Number(result[0].lat),lon:Number(result[0].lon)};cache[hotel.name]=location;localStorage.setItem(GEO_CACHE,JSON.stringify(cache));return{...location,approx:false};}}catch{}return{lat:hotel.fallback[0],lon:hotel.fallback[1],approx:true};}
async function renderMap(routes:RouteDay[]):Promise<void>{const map=L.map("map",{scrollWheelZoom:false}).setView([26.48,127.93],9);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap contributors"}).addTo(map);const routeLayer=L.layerGroup().addTo(map);const hotelLayer=L.layerGroup().addTo(map);L.control.layers(undefined,{"單車路線":routeLayer,"住宿":hotelLayer},{collapsed:false}).addTo(map);const colors=["#0077b6","#00a896","#f4a261","#e76f51","#7b2cbf","#6a4c93"];const bounds:L.LatLngExpression[]=[];routes.forEach((r,i)=>{const latlngs=routeLatLngs(r);if(r.geojson?.type==="MultiLineString"){(latlngs as L.LatLngExpression[][]).forEach(line=>L.polyline(line,{color:colors[i%colors.length],weight:5,opacity:.85}).addTo(routeLayer));}else{L.polyline(latlngs as L.LatLngExpression[],{color:colors[i%colors.length],weight:5,opacity:.85}).bindPopup(`<b>Day ${r.day}</b><br>${r.title}`).addTo(routeLayer);}r.waypoints.forEach(w=>{L.circleMarker([w.lat,w.lon],{radius:5,color:"#fff",weight:2,fillColor:colors[i%colors.length],fillOpacity:1}).bindPopup(w.name).addTo(routeLayer);bounds.push([w.lat,w.lon]);});});const locations=await Promise.all(hotels.map(async hotel=>({hotel,location:await hotelLocation(hotel)})));locations.forEach(({hotel,location})=>{const popup=`<b>🏨 ${hotel.name}</b><br>${hotel.dates} ・ ${hotel.area}<br>${location.approx?'<small>地圖位置為地區中心，請以 Google Maps 搜尋結果為準。</small><br>':''}<a href="${mapsUrl(hotel.query)}" target="_blank" rel="noopener">Google Maps ↗</a>`;L.circleMarker([location.lat,location.lon],{radius:8,color:"#fff",weight:2,fillColor:"#d97706",fillOpacity:1}).bindPopup(popup).addTo(hotelLayer);bounds.push([location.lat,location.lon]);});if(bounds.length)map.fitBounds(bounds as L.LatLngBoundsExpression,{padding:[20,20]});}
function renderLists():void{q<HTMLElement>("#poke-list").innerHTML=poke.map(([name,mons,lat,lon],i)=>`<label class="poi"><input type="checkbox" data-save="poke-${i}" data-group="poke"><span><b>${name}</b><br><span class="muted">${mons}</span><br><a target="_blank" href="https://www.google.com/maps?q=${lat},${lon}">地圖 ↗</a></span></label>`).join("");q<HTMLElement>("#prep-list").innerHTML=prep.map(([name,desc],i)=>`<label class="poi"><input type="checkbox" data-save="prep-${i}"><span><b>${name}</b><br><span class="muted">${desc}</span></span></label>`).join("");document.querySelectorAll<HTMLInputElement>("[data-save]").forEach(x=>x.addEventListener("change",save));restore();}
function updateProgress():void{const pc=[...document.querySelectorAll<HTMLInputElement>('[data-group="poke"]')].filter(x=>x.checked).length;q<HTMLElement>("#poke-count").textContent=`${pc} / ${poke.length}`;q<HTMLElement>("#poke-bar").style.width=`${pc/poke.length*100}%`;q<HTMLElement>("#cert-poke").textContent=`${pc} / ${poke.length}`;}
function setupCertificate():void{q<HTMLButtonElement>("#cert-update").addEventListener("click",()=>{q<HTMLElement>("#cert-name-out").textContent=q<HTMLInputElement>("#cert-name").value.trim()||"RR";q<HTMLElement>("#cert-date-out").textContent="完成日期："+(q<HTMLInputElement>("#cert-date").value||"—");q<HTMLElement>("#cert-km-out").textContent=(q<HTMLInputElement>("#cert-km").value||"—")+" km";q<HTMLElement>("#cert-elev-out").textContent=(q<HTMLInputElement>("#cert-elev").value||"—")+" m";updateProgress();});}
(async()=>{renderLists();setupCertificate();const routes=await loadRoutes();renderRoutes(routes);await renderMap(routes);})();
